# Generated by Django 4.2.1 on 2024-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_author_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
